en:
  languageName: English
  weight: 1

zh-hans:
  languageName: 简体中文
  weight: 4
  params:
    description: Personal site incl. notes, blogs and essays.
    keywords: 'blogs, programming languages, software development, China history, reading, travel, shanghai'
    archive:
      dateFormat: 01-02
