# Site settings
title: Bruce Jia - Software Developer
description: "Yet another blog which will long last... really?"
baseurl: "" # set this to url like '/blog'
url: "http://brucejia.net/" # set this to real url. Especially if you have your own domain name.
# User settings
username: Bruce Jia
user_title: Bruce Jia
email: jiafangtao@gmail.com
twitter_username: brucejia
github_username:  jiafangtao
gplus_username:  jiafangtao
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: worklog
    url: https://github.com/jiafangtao/worklog
  - name: player.js
    url: https://github.com/jiafangtao/player.js 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
